Query for checking the store for dupes:

select count(zemailaddress) from (select zemailaddress, c from (select zemailaddress, count(zemailaddress) c from zperson group by zemailaddress) where c > 1);

- (void)populateStore {
    NSURL *storesDirectory = [NSURL fileURLWithPath:[NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES) lastObject]];
    storesDirectory = [storesDirectory URLByAppendingPathComponent:@"SharedCoreDataStores"];
    
    if (NO == [[NSFileManager defaultManager] fileExistsAtPath:[storesDirectory path]]) {
        //create it
        NSError *error = nil;
        if ([[NSFileManager defaultManager] createDirectoryAtURL:storesDirectory withIntermediateDirectories:YES attributes:nil error:&error] == NO) {
            NSLog(@"Unable to create application sandbox stores directory: %@\n\tError: %@", storesDirectory, error);
        }
    }
    
    NSError *error = nil;
    NSURL *storeURL = [storesDirectory URLByAppendingPathComponent:@"seedStore.sqlite"];
    if (nil == [_coreDataController.psc addPersistentStoreWithType:NSSQLiteStoreType configuration:@"CloudConfig" URL:storeURL options:nil error:&error]) {
        NSLog(@"Error: %@", error);
        abort();
    }
    
    //add the 50 states and outlying territories
    NSArray *firstNames = @[ @"1:LIAM",
    @"1:CHARLOTTE",
    @"2:NOAH",
    @"2:SOPHIA/SOFIA",
    @"3:AIDAN/AIDEN/ADEN",
    @"3:AMELIA/EMILIA",
    @"4:JACKSON/JAXON",
    @"4:OLIVIA",
    @"5:CALEB/KALEB",
    @"5:AVA",
    @"6:OLIVER",
    @"6:LILY/LILLY",
    @"7:GRAYSON/GREYSON",
    @"7:EMMA",
    @"8:ETHAN",
    @"8:SCARLETT/SCARLET",
    @"9:ALEXANDER",
    @"9:AUDREY",
    @"10:OWEN",
    @"10:HARPER",
    @"11:BENJAMIN",
    @"11:ABIGAIL",
    @"12:LUCAS/LUKAS",
    @"12:CHLOE/KHLOE",
    @"13:LANDON/LANDEN",
    @"13:ELLA",
    @"14:ASHER",
    @"14:VIOLET",
    @"15:ELIJAH",
    @"15:ELIZABETH/ELISABETH",
    @"16:DECLAN",
    @"16:ARIA",
    @"17:CAYDEN/CADEN/KAYDEN/KADEN",
    @"17:ISABELLA",
    @"18:JACOB/JAKOB",
    @"18:CLAIRE/CLARE",
    @"19:MASON",
    @"19:MADELINE/MADELYN",
    @"20:LEVI",
    @"20:GRACE" ];
    
    NSArray *lastNames = @[ @"Alfort",
    @"Allendorf",
    @"Alsop",
    @"Amaker",
    @"Angus",
    @"Annan",
    @"Annesley",
    @"Appleby",
    @"Arbuthnot",
    @"Armitage",
    @"Artois",
    @"Arundel",
    @"Ashburton",
    @"Astor",
    @"Athill",
    @"Athow",
    @"Auchinleck",
    @"Averill",
    @"Ayres",
    @"Balcombe",
    @"Balfour",
    @"Ballantine",
    @"Ballantyne",
    @"Bancroft",
    @"Bannatyne",
    @"Bar",
    @"Barnum",
    @"Barnwell",
    @"Barringer",
    @"Barrow",
    @"Barry",
    @"Barstow",
    @"Barwick;Berwick",
    @"Beal",
    @"Beckett",
    @"Beckley;Beakley",
    @"Beckwith",
    @"Bedford",
    @"Beers",
    @"Bellamy",
    @"Belvidere",
    @"Bentley",
    @"Bethune",
    @"Beveridge",
    @"Beverly",
    @"Biggar",
    @"Billings",
    @"Bingham",
    @"Binney",
    @"Birch",
    @"Birnie;Birney",
    @"Blackwood",
    @"Blaisdale",
    @"Blaney",
    @"Bloss",
    @"Bogue",
    @"Bolingbroke",
    @"Bolton",
    @"Bonar",
    @"Boswell",
    @"Boughton",
    @"Bourne",
    @"Boynton",
    @"Bradford",
    @"Braine",
    @"Brandon",
    @"Breck",
    @"Breckenridge",
    @"Brentwood",
    @"Briare",
    @"Bridge;Bridges",
    @"Brienne",
    @"Brierly",
    @"Brighton",
    @"Brocklesby",
    @"Brodt",
    @"Bromfield;Broomfield",
    @"Bromley",
    @"Brooks",
    @"Brougham",
    @"Broughton",
    @"Bryne",
    @"Buchan",
    @"Buchanan",
    @"Buckbee",
    @"Buddington",
    @"Bulkeley;Buckley",
    @"Bunnell",
    @"Burbeck",
    @"Burgos",
    @"Burgoyne",
    @"Burleigh",
    @"Burnham",
    @"Burns",
    @"Burrard",
    @"Burton",
    @"Bushwell",
    @"Butman",
    @"Buxton",
    @"Cadwell",
    @"Calder",
    @"Caldwell",
    @"Carden",
    @"Carey;Cary",
    @"Carmichael",
    @"Caw",
    @"Caxton",
    @"Cayly",
    @"Chadwick",
    @"Challoner",
    @"Chatham;Chetham",
    @"Chatsey;Chadsey",
    @"Chatsworth",
    @"Chatterton",
    @"Chedsey",
    @"Chesebrough",
    @"Chester",
    @"Chichester",
    @"Chilton",
    @"Church",
    @"Clauson",
    @"Clavering",
    @"Clay",
    @"Cleveland",
    @"Cliff",
    @"Clifton",
    @"Clum",
    @"Cobb",
    @"Cobern",
    @"Cochran",
    @"Cockburn",
    @"Coffin",
    @"Coggeshall;Cogswell",
    @"Colby",
    @"Collamore",
    @"Colley",
    @"Colquite;Colquoit",
    @"Colton",
    @"Colven;Colvin",
    @"Conry",
    @"Contin",
    @"Conyers",
    @"Coote",
    @"Corbin",
    @"Cornish",
    @"Cornwallis",
    @"Corrie",
    @"Cotesworth",
    @"Courtenay",
    @"Coventry",
    @"Cranston;Cranstoun",
    @"Crawford",
    @"Crayford",
    @"Croft",
    @"Cross",
    @"Crosswell",
    @"Cullen",
    @"Cummings",
    @"Cunningham",
    @"Cupar",
    @"D'Oily",
    @"Daggett",
    @"Dalrymple",
    @"Dalton",
    @"Danforth;Danford",
    @"Darby",
    @"Davenport",
    @"De Wilde",
    @"Dearden",
    @"Denio",
    @"Derby",
    @"Devenish",
    @"Devlin",
    @"Digby",
    @"Dinsmor",
    @"Dolbeer",
    @"Dole",
    @"Dorset",
    @"Dudley",
    @"Dumfries",
    @"Dun",
    @"Dunbar",
    @"Dunham",
    @"Dunipace",
    @"Duppa",
    @"Durban",
    @"Durden",
    @"Durham",
    @"Dutton",
    @"Dyke",
    @"Eastcote",
    @"Eberlee",
    @"Edgecumbe",
    @"Elphinstone",
    @"Ely",
    @"Emmet",
    @"Esham",
    @"Eton",
    @"Eure",
    @"Evelyn",
    @"Ewell",
    @"Fairholm",
    @"Fales",
    @"Falun",
    @"Fanshaw",
    @"Farnham",
    @"Fay",
    @"Felton",
    @"Ferrer;Ferrers",
    @"Fife",
    @"Fifield",
    @"Filey;Filley",
    @"Flanders",
    @"Fleming",
    @"Flint",
    @"Foote",
    @"Forbes",
    @"Fordham",
    @"Fosdyke",
    @"Fotherby",
    @"Fothergill",
    @"Fotheringham",
    @"Fremont",
    @"Frothingham",
    @"Fulham",
    @"Fulsom",
    @"Gano",
    @"Garfield",
    @"Garnet",
    @"Garrison",
    @"Gaston",
    @"Gavet",
    @"Geddes;Getty",
    @"Gihon",
    @"Gill",
    @"Girdwood",
    @"Girvan",
    @"Glanville",
    @"Glentworth",
    @"Gliston",
    @"Gloucester",
    @"Goadby",
    @"Goring",
    @"Goudy",
    @"Grasse",
    @"Gray",
    @"Greely",
    @"Grimsby",
    @"Hadley",
    @"Haineau",
    @"Halden",
    @"Hales",
    @"Halsey",
    @"Halstead",
    @"Ham",
    @"Hamlin",
    @"Hampton",
    @"Hanley",
    @"Hanna",
    @"Harcourt",
    @"Harding",
    @"Hargill",
    @"Harley;Harleigh;Harlow",
    @"Harrington",
    @"Hartwell",
    @"Hasbrouck",
    @"Hastings",
    @"Hatch",
    @"Hatfield",
    @"Hathaway",
    @"Hatton",
    @"Haverill",
    @"Hayden;Haydyn",
    @"Hedges",
    @"Hedon",
    @"Helling",
    @"Henley",
    @"Herndon",
    @"Hernshaw",
    @"Heyden",
    @"Hinckley",
    @"Hindon;Hinton",
    @"Hippisley",
    @"Hipwood",
    @"Holbech",
    @"Holland",
    @"Holme;Holmes",
    @"Holsapple",
    @"Holt",
    @"Holywell",
    @"Hope",
    @"Horton",
    @"Hosford",
    @"Hough",
    @"Houghton",
    @"Houston",
    @"Hubbell",
    @"Huddleston",
    @"Hull",
    @"Hungerford",
    @"Huntley",
    @"Hutton",
    @"Hyde",
    @"Incledon",
    @"Ingham",
    @"Ingleby;Ingoldsby",
    @"Ipres",
    @"Ireton",
    @"Irving;Irvine",
    @"Isabel",
    @"Isham",
    @"Islip",
    @"Ives",
    @"Kay",
    @"Keith",
    @"Kelsey",
    @"Kelso",
    @"Kendall",
    @"Kent",
    @"Kettle",
    @"Kilburne",
    @"Kilham",
    @"Kinghorn",
    @"Kingston",
    @"Kinloch",
    @"Kirby",
    @"Kirkaldy",
    @"Kirkham",
    @"Kirkpatrick",
    @"Knox",
    @"Kyle",
    @"Lacy",
    @"Lancaster",
    @"Langton",
    @"Laycock",
    @"Lechmere",
    @"Leigh;Legh",
    @"Leland",
    @"Lester;Leicester;Leycester",
    @"Leven",
    @"Lewes",
    @"Lewknor",
    @"Lincoln",
    @"Lindall",
    @"Lindsay;Lindsey",
    @"Linn;Linne",
    @"Linton",
    @"Lippencot",
    @"Lismore",
    @"Livingstone",
    @"Lonsdale",
    @"Ludlow",
    @"Main;Mayne",
    @"Mansfield",
    @"Mansle",
    @"Mar",
    @"Massey;Massie",
    @"Mayo",
    @"Mead",
    @"Medcaf",
    @"Menteth;Monteith",
    @"Merton",
    @"Meyeul",
    @"Middleditch",
    @"Middleton",
    @"Milbourne",
    @"Mills",
    @"Milthorpe",
    @"Milton",
    @"Moffatt",
    @"Monroe",
    @"Morley",
    @"Moseley",
    @"Moxley",
    @"Mundy",
    @"Munsel",
    @"Murray;Moray",
    @"Nairne",
    @"Nance",
    @"Needham",
    @"Newton",
    @"Nisbett",
    @"Nogent",
    @"Norcutt;Northcote",
    @"Norfolk",
    @"Northop",
    @"Northumberland",
    @"Norton",
    @"Norwich",
    @"Nottingham",
    @"Oakham",
    @"Ockham",
    @"Ogilvie",
    @"Ollendorff",
    @"Olmstead",
    @"Onslow",
    @"Orchard",
    @"Orr",
    @"Orton",
    @"Otter",
    @"Ouseley",
    @"Oxford",
    @"Pangbourn",
    @"Paris",
    @"Parret;Perrot",
    @"Parsall",
    @"Parshall",
    @"Paxton",
    @"Pedin",
    @"Peebles",
    @"Peele",
    @"Pelham",
    @"Pendleton",
    @"Peney",
    @"Pennington",
    @"Percy;Piercy;Percey",
    @"Pevensey",
    @"Pickering",
    @"Pickersgill",
    @"Playfair",
    @"Pleasants",
    @"Polley",
    @"Pollock",
    @"Poole",
    @"Poulton",
    @"Pressley",
    @"Preston",
    @"Pringle",
    @"Radcliff",
    @"Ralston",
    @"Ramsey",
    @"Ranney",
    @"Rawdon",
    @"Reddenhurst",
    @"Rhodes",
    @"Riddell",
    @"Ripley",
    @"Rochester",
    @"Romanno",
    @"Root",
    @"Rowe",
    @"Rowen",
    @"Rue",
    @"Rusbridge",
    @"Rutherford",
    @"Rynders",
    @"Safford",
    @"Sandford",
    @"Saterlee",
    @"Scarret",
    @"Scroggs",
    @"Seaford",
    @"Seaforth",
    @"Seaton",
    @"Selby",
    @"Selkirk",
    @"Seton",
    @"Severn",
    @"Shaddock;Schadeck",
    @"Shelley",
    @"Sheppy",
    @"Shiel",
    @"Shrewsbury",
    @"Shuckburgh",
    @"Shurtliff",
    @"Shute",
    @"Slade",
    @"Snodgrass",
    @"Soule",
    @"Southwell",
    @"Spalding",
    @"St. Albans",
    @"Stanhope",
    @"Stanley",
    @"Stebbins;Stubbins",
    @"Stein",
    @"Stirling",
    @"Stocking",
    @"Stockton",
    @"Stokes",
    @"Stokesby;Stukeby",
    @"Stone",
    @"Stoughton",
    @"Strain",
    @"Sunderland",
    @"Surtees",
    @"Sutton",
    @"Swift",
    @"Swinburn",
    @"Symington",
    @"Tabor",
    @"Tattersall",
    @"Teddington",
    @"Teesdale",
    @"Tefft;Teft",
    @"Telfair",
    @"Telford",
    @"Temes",
    @"Thorn",
    @"Thurston",
    @"Thwaite;Thwaytes",
    @"Tichenor",
    @"Tillinghast",
    @"Tilton",
    @"Ting",
    @"Torry",
    @"Toucey",
    @"Tournay",
    @"Tracy;Tracey",
    @"Troublefield",
    @"Trowbridge",
    @"True",
    @"Tuthill;Tuttle",
    @"Twickenham",
    @"Van Alstyne",
    @"Van Amee;Van Namen;Van Name",
    @"Van Arden;Van Aerden;Van Orden",
    @"Van Arnhem;Van Arnum;Van Ornum",
    @"Van Dam",
    @"Van Horn;Van Hoorn",
    @"Van Huisen;Van Hoosen;Van Husen",
    @"Van Ingen",
    @"Van Loon",
    @"Van Ness",
    @"Van Rensselaer",
    @"Van Schaack;Van Schaick;Van Scheyk",
    @"Van Slyck",
    @"Van Stantvoordt",
    @"Van Volkenburg",
    @"Van Vorst;Van Voorst",
    @"Van Woert;Van Wort",
    @"Van Wyck",
    @"Vesey",
    @"Vielle;Velay",
    @"Vine",
    @"Waite",
    @"Wakefield",
    @"Wallop",
    @"Walpole",
    @"Walton",
    @"Wample;Wemple",
    @"Wands",
    @"Warburton",
    @"Wardlaw",
    @"Ware",
    @"Warwick",
    @"Washington",
    @"Wassen",
    @"Waters",
    @"Way",
    @"Wayland;Weyland",
    @"Weeden",
    @"Welby",
    @"Welden",
    @"Wells",
    @"Wemyss",
    @"Wentworth",
    @"Westmoreland",
    @"Wetherby",
    @"Wetherspoon;Witherspoon;Wodderspoon",
    @"Wheaton",
    @"Whittaker",
    @"Wigan;Wiggin",
    @"Wilberforce",
    @"Willoughby",
    @"Wilton",
    @"Wiltshire",
    @"Winch",
    @"Winchester",
    @"Windham",
    @"Windsor",
    @"Wing",
    @"Wingfield",
    @"Winslow",
    @"Winterton",
    @"Winthrop",
    @"Wire;Weir;Ware",
    @"Wiswall",
    @"Wolsey;Woolsey",
    @"Woolley",
    @"Worcester",
    @"York" ];
    
    NSArray *stateLocations = @[ @"US-AL:Alabama:state",
    @"US-AK:Alaska:state",
    @"US-AZ:Arizona:state",
    @"US-AR:Arkansas:state",
    @"US-CA:California:state",
    @"US-CO:Colorado:state",
    @"US-CT:Connecticut:state",
    @"US-DE:Delaware:state",
    @"US-FL:Florida:state",
    @"US-GA:Georgia:state",
    @"US-HI:Hawaii:state",
    @"US-ID:Idaho:state",
    @"US-IL:Illinois:state",
    @"US-IN:Indiana:state",
    @"US-IA:Iowa:state",
    @"US-KS:Kansas:state",
    @"US-KY:Kentucky:state",
    @"US-LA:Louisiana:state",
    @"US-ME:Maine:state",
    @"US-MD:Maryland:state",
    @"US-MA:Massachusetts:state",
    @"US-MI:Michigan:state",
    @"US-MN:Minnesota:state",
    @"US-MS:Mississippi:state",
    @"US-MO:Missouri:state",
    @"US-MT:Montana:state",
    @"US-NE:Nebraska:state",
    @"US-NV:Nevada:state",
    @"US-NH:New Hampshire:state",
    @"US-NJ:New Jersey:state",
    @"US-NM:New Mexico:state",
    @"US-NY:New York:state",
    @"US-NC:North Carolina:state",
    @"US-ND:North Dakota:state",
    @"US-OH:Ohio:state",
    @"US-OK:Oklahoma:state",
    @"US-OR:Oregon:state",
    @"US-PA:Pennsylvania:state",
    @"US-RI:Rhode Island:state",
    @"US-SC:South Carolina:state",
    @"US-SD:South Dakota:state",
    @"US-TN:Tennessee:state",
    @"US-TX:Texas:state",
    @"US-UT:Utah:state",
    @"US-VT:Vermont:state",
    @"US-VA:Virginia:state",
    @"US-WA:Washington:state",
    @"US-WV:West Virginia:state",
    @"US-WI:Wisconsin:state",
    @"US-WY:Wyoming:state",
    @"US-DC:District of Columbia:district",
    @"US-AS:American Samoa:outlying territory",
    @"US-GU:Guam:outlying territory",
    @"US-MP:Northern Mariana Islands:outlying territory",
    @"US-PR:Puerto Rico:outlying territory",
    @"US-UM:United States Minor Outlying Islands:outlying territory",
    @"US-VI:Virgin Islands, U.S.:outlying territory" ];
    
    NSUInteger i = 0;
    NSUInteger j = 0;
    for (NSString *lastName in lastNames) {
        j++; //because 170k records is too much
        if (0 != (j % 10)) {
            continue;
        }
        
        NSArray *lastNameVariations = [lastName componentsSeparatedByString:@";"];
        for (NSString *lastNameVariation in lastNameVariations) {
            for (NSString *firstName in firstNames) {
                NSArray *components = [firstName componentsSeparatedByString:@":"];
                NSString *firstNameVariationsString = [components objectAtIndex:1];
                NSArray *firstNameVariations = [firstNameVariationsString componentsSeparatedByString:@"/"];
                for (NSString *firstNameVariation in firstNameVariations) {
                    NSMutableString *camelCaseFirstName = [[NSMutableString alloc] initWithCapacity:[firstNameVariation length]];
                    
                    [camelCaseFirstName appendString:[firstNameVariation substringWithRange:NSMakeRange(0, 1)]];
                    [camelCaseFirstName appendString:[[firstNameVariation substringWithRange:NSMakeRange(1, [firstNameVariation length] - 1)] lowercaseString]];
                    
                    //make the email address first initial.lastname@test.com
                    NSString *emailAddress = [[NSString stringWithFormat:@"%@.%@@test.com", camelCaseFirstName, lastNameVariation] lowercaseString];
                    
                    Person *p = [NSEntityDescription insertNewObjectForEntityForName:@"Person" inManagedObjectContext:_coreDataController.mainThreadContext];
                    p.firstName = camelCaseFirstName;
                    p.lastName = lastNameVariation;
                    p.emailAddress = emailAddress;
                    p.recordUUID = [[NSUUID UUID] UUIDString];
                    p.stateISOCode = [[[stateLocations objectAtIndex:(i % [stateLocations count])] componentsSeparatedByString:@":"] objectAtIndex:0];
                    i++;
                }
            }
        }
        
    }
    
    [_coreDataController.mainThreadContext performBlockAndWait:^{
        [_coreDataController.mainThreadContext save:nil];
    }];
}

- (void)populateStore {
    NSURL *storesDirectory = [NSURL fileURLWithPath:[NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES) lastObject]];
    storesDirectory = [storesDirectory URLByAppendingPathComponent:@"SharedCoreDataStores"];
    
    if (NO == [[NSFileManager defaultManager] fileExistsAtPath:[storesDirectory path]]) {
        //create it
        NSError *error = nil;
        if ([[NSFileManager defaultManager] createDirectoryAtURL:storesDirectory withIntermediateDirectories:YES attributes:nil error:&error] == NO) {
            NSLog(@"Unable to create application sandbox stores directory: %@\n\tError: %@", storesDirectory, error);
        }
    }
    
    NSError *error = nil;
    NSURL *storeURL = [storesDirectory URLByAppendingPathComponent:@"seedStore.sqlite"];
    if (nil == [_coreDataController.psc addPersistentStoreWithType:NSSQLiteStoreType configuration:@"CloudConfig" URL:storeURL options:nil error:&error]) {
        NSLog(@"Error: %@", error);
        abort();
    }
    
    //add the 50 states and outlying territories
    NSArray *firstNames = @[ @"1:LIAM",
    @"1:CHARLOTTE",
    @"2:NOAH",
    @"2:SOPHIA/SOFIA",
    @"3:AIDAN/AIDEN/ADEN",
    @"3:AMELIA/EMILIA",
    @"4:JACKSON/JAXON",
    @"4:OLIVIA",
    @"5:CALEB/KALEB",
    @"5:AVA",
    @"6:OLIVER",
    @"6:LILY/LILLY",
    @"7:GRAYSON/GREYSON",
    @"7:EMMA",
    @"8:ETHAN",
    @"8:SCARLETT/SCARLET",
    @"9:ALEXANDER",
    @"9:AUDREY",
    @"10:OWEN",
    @"10:HARPER",
    @"11:BENJAMIN",
    @"11:ABIGAIL",
    @"12:LUCAS/LUKAS",
    @"12:CHLOE/KHLOE",
    @"13:LANDON/LANDEN",
    @"13:ELLA",
    @"14:ASHER",
    @"14:VIOLET",
    @"15:ELIJAH",
    @"15:ELIZABETH/ELISABETH",
    @"16:DECLAN",
    @"16:ARIA",
    @"17:CAYDEN/CADEN/KAYDEN/KADEN",
    @"17:ISABELLA",
    @"18:JACOB/JAKOB",
    @"18:CLAIRE/CLARE",
    @"19:MASON",
    @"19:MADELINE/MADELYN",
    @"20:LEVI",
    @"20:GRACE",
    @"21:CONNOR/CONOR",
    @"21:LILA/LILAH",
    @"22:WILLIAM",
    @"22:ARIANNA/ARIANA",
    @"23:HENRY",
    @"23:NORA/NORAH",
    @"24:GABRIEL",
    @"24:LAYLA/LEILA",
    @"25:GAVIN",
    @"25:LUCY/LUCIE",
    @"26:LOGAN",
    @"26:AVERY",
    @"27:ELLIOT/ELIOT/ELLIOTT",
    @"27:STELLA",
    @"28:JAMES",
    @"28:AUBREY/AUBREE",
    @"30:FINN/FYNN",
    @"30:HANNAH",
    @"31:EMMETT/EMMET",
    @"31:SAVANNAH/SAVANNA",
    @"32:ISAAC",
    @"32:ADDISON/ADDYSON",
    @"33:ANDREW",
    @"33:EVELYN",
    @"34:WYATT",
    @"34:ADALYN",
    @"35:CARTER",
    @"35:VIVIENNE/VIVIEN/VIVIAN",
    @"36:COLE/KOLE",
    @"36:ISABELLE/ISABEL",
    @"37:COLIN/COLLIN",
    @"37:SOPHIE/SOFIE",
    @"38:NATHAN",
    @"38:AURORA",
    @"39:ELI",
    @"39:JULIET/JULIETTE",
    @"40:SAMUEL",
    @"40:NATALIE",
    @"41:DYLAN/DILLON/DILLAN",
    @"41:ISLA",
    @"42:MICAH",
    @"42:EMILY",
    @"43:SEBASTIAN/SEBASTIEN",
    @"43:CLARA",
    @"44:PARKER",
    @"44:EVANGELINE",
    @"45:MILES/MYLES",
    @"45:LEAH",
    @"46:JONAH",
    @"46:PENELOPE",
    @"47:BRADEN/BRAYDEN",
    @"47:CATHERINE/KATHERINE",
    @"48:NICHOLAS/NICOLAS",
    @"48:CAROLINE",
    @"49:HUDSON",
    @"49:SADIE",
    @"50:ZACHARY",
    @"50:ADELE/ADELLE",
    @"51:CHASE",
    @"51:GENEVIEVE",
    @"52:LUKE",
    @"52:PAIGE",
    @"53:JUDE",
    @"53:ANNA/ANA",
    @"54:HOLDEN",
    @"54:MIA",
    @"55:EVAN",
    @"55:LORELEI",
    @"56:IAN",
    @"56:LYDIA",
    @"57:NATHANIEL",
    @"57:EDEN",
    @"58:BENTLEY",
    @"58:ADELAIDE",
    @"59:TRISTAN",
    @"59:ANNABELLE",
    @"60:MATTHEW",
    @"60:WILLOW",
    @"61:DOMINIC/DOMINICK",
    @"61:BRIELLE",
    @"62:JOSHUA",
    @"62:PIPER",
    @"63:SAWYER",
    @"63:ZOE",
    @"64:NOLAN",
    @"64:QUINN",
    @"65:JASPER",
    @"65:PAYTON/PEYTON",
    @"66:AARON",
    @"66:HAYLEY/HALEY/HAILEY",
    @"67:SILAS",
    @"67:ZOEY",
    @"68:JAYDEN/JADEN/JADON",
    @"68:LILLIAN",
    @"69:DANIEL",
    @"69:ELEANOR",
    @"70:BENNETT",
    @"70:RUBY",
    @"71:RYDER/RIDER",
    @"71:AUTUMN",
    @"72:ADAM",
    @"72:KEIRA/KIRA",
    @"73:BLAKE",
    @"73:MOLLY",
    @"74:RYAN",
    @"74:TEAGAN/TEGAN",
    @"75:ISAIAH",
    @"75:BROOKLYN/BROOKLYNN",
    @"76:XAVIER",
    @"76:RILEY/RYLEE",
    @"77:COLTON",
    @"77:BELLA",
    @"78:MAX",
    @"78:FIONA",
    @"79:SETH",
    @"79:ROSALIE",
    @"80:CARSON/KARSON/KARSEN",
    @"80:EVA",
    @"81:HUNTER",
    @"81:SIENNA",
    @"82:MICHAEL",
    @"82:VICTORIA",
    @"83:COOPER",
    @"83:ELISE/ELYSE",
    @"84:EVERETT",
    @"84:GABRIELLA",
    @"85:CHARLES",
    @"85:DELILAH",
    @"86:EZRA",
    @"86:MADISON/MADDISON",
    @"87:THEODORE",
    @"87:CORA",
    @"88:BRODY",
    @"88:ARABELLA",
    @"89:CAMERON/KAMERON",
    @"89:IVY",
    @"90:JULIAN",
    @"90:AALIYAH/ALEAH",
    @"91:LEO",
    @"91:ALYSSA/ALISSA",
    @"92:AUSTIN",
    @"92:SAMANTHA",
    @"93:ARCHER",
    @"93:REAGAN/REGAN",
    @"94:JACE",
    @"94:SARAH/SARA",
    @"95:ADRIAN",
    @"95:NAOMI",
    @"96:HARRISON",
    @"96:CADENCE/KADENCE",
    @"97:THOMAS",
    @"97:JULIA",
    @"98:JOSEPH",
    @"98:ALEXIS",
    @"99:JOHN",
    @"99:HAZEL",
    @"100:TYLER",
    @"100:LAUREN" ];
    
    NSArray *lastNames = @[ @"Alfort",
    @"Allendorf",
    @"Alsop",
    @"Amaker",
    @"Angus",
    @"Annan",
    @"Annesley",
    @"Appleby",
    @"Arbuthnot",
    @"Armitage",
    @"Artois",
    @"Arundel",
    @"Ashburton",
    @"Astor",
    @"Athill",
    @"Athow",
    @"Auchinleck",
    @"Averill",
    @"Ayres",
    @"Balcombe",
    @"Balfour",
    @"Ballantine",
    @"Ballantyne",
    @"Bancroft",
    @"Bannatyne",
    @"Bar",
    @"Barnum",
    @"Barnwell",
    @"Barringer",
    @"Barrow",
    @"Barry",
    @"Barstow",
    @"Barwick;Berwick",
    @"Beal",
    @"Beckett",
    @"Beckley;Beakley",
    @"Beckwith",
    @"Bedford",
    @"Beers",
    @"Bellamy",
    @"Belvidere",
    @"Bentley",
    @"Bethune",
    @"Beveridge",
    @"Beverly",
    @"Biggar",
    @"Billings",
    @"Bingham",
    @"Binney",
    @"Birch",
    @"Birnie;Birney",
    @"Blackwood",
    @"Blaisdale",
    @"Blaney",
    @"Bloss",
    @"Bogue",
    @"Bolingbroke",
    @"Bolton",
    @"Bonar",
    @"Boswell",
    @"Boughton",
    @"Bourne",
    @"Boynton",
    @"Bradford",
    @"Braine",
    @"Brandon",
    @"Breck",
    @"Breckenridge",
    @"Brentwood",
    @"Briare",
    @"Bridge;Bridges",
    @"Brienne",
    @"Brierly",
    @"Brighton",
    @"Brocklesby",
    @"Brodt",
    @"Bromfield;Broomfield",
    @"Bromley",
    @"Brooks",
    @"Brougham",
    @"Broughton",
    @"Bryne",
    @"Buchan",
    @"Buchanan",
    @"Buckbee",
    @"Buddington",
    @"Bulkeley;Buckley",
    @"Bunnell",
    @"Burbeck",
    @"Burgos",
    @"Burgoyne",
    @"Burleigh",
    @"Burnham",
    @"Burns",
    @"Burrard",
    @"Burton",
    @"Bushwell",
    @"Butman",
    @"Buxton",
    @"Cadwell",
    @"Calder",
    @"Caldwell",
    @"Carden",
    @"Carey;Cary",
    @"Carmichael",
    @"Caw",
    @"Caxton",
    @"Cayly",
    @"Chadwick",
    @"Challoner",
    @"Chatham;Chetham",
    @"Chatsey;Chadsey",
    @"Chatsworth",
    @"Chatterton",
    @"Chedsey",
    @"Chesebrough",
    @"Chester",
    @"Chichester",
    @"Chilton",
    @"Church",
    @"Clauson",
    @"Clavering",
    @"Clay",
    @"Cleveland",
    @"Cliff",
    @"Clifton",
    @"Clum",
    @"Cobb",
    @"Cobern",
    @"Cochran",
    @"Cockburn",
    @"Coffin",
    @"Coggeshall;Cogswell",
    @"Colby",
    @"Collamore",
    @"Colley",
    @"Colquite;Colquoit",
    @"Colton",
    @"Colven;Colvin",
    @"Conry",
    @"Contin",
    @"Conyers",
    @"Coote",
    @"Corbin",
    @"Cornish",
    @"Cornwallis",
    @"Corrie",
    @"Cotesworth",
    @"Courtenay",
    @"Coventry",
    @"Cranston;Cranstoun",
    @"Crawford",
    @"Crayford",
    @"Croft",
    @"Cross",
    @"Crosswell",
    @"Cullen",
    @"Cummings",
    @"Cunningham",
    @"Cupar",
    @"D'Oily",
    @"Daggett",
    @"Dalrymple",
    @"Dalton",
    @"Danforth;Danford",
    @"Darby",
    @"Davenport",
    @"De Wilde",
    @"Dearden",
    @"Denio",
    @"Derby",
    @"Devenish",
    @"Devlin",
    @"Digby",
    @"Dinsmor",
    @"Dolbeer",
    @"Dole",
    @"Dorset",
    @"Dudley",
    @"Dumfries",
    @"Dun",
    @"Dunbar",
    @"Dunham",
    @"Dunipace",
    @"Duppa",
    @"Durban",
    @"Durden",
    @"Durham",
    @"Dutton",
    @"Dyke",
    @"Eastcote",
    @"Eberlee",
    @"Edgecumbe",
    @"Elphinstone",
    @"Ely",
    @"Emmet",
    @"Esham",
    @"Eton",
    @"Eure",
    @"Evelyn",
    @"Ewell",
    @"Fairholm",
    @"Fales",
    @"Falun",
    @"Fanshaw",
    @"Farnham",
    @"Fay",
    @"Felton",
    @"Ferrer;Ferrers",
    @"Fife",
    @"Fifield",
    @"Filey;Filley",
    @"Flanders",
    @"Fleming",
    @"Flint",
    @"Foote",
    @"Forbes",
    @"Fordham",
    @"Fosdyke",
    @"Fotherby",
    @"Fothergill",
    @"Fotheringham",
    @"Fremont",
    @"Frothingham",
    @"Fulham",
    @"Fulsom",
    @"Gano",
    @"Garfield",
    @"Garnet",
    @"Garrison",
    @"Gaston",
    @"Gavet",
    @"Geddes;Getty",
    @"Gihon",
    @"Gill",
    @"Girdwood",
    @"Girvan",
    @"Glanville",
    @"Glentworth",
    @"Gliston",
    @"Gloucester",
    @"Goadby",
    @"Goring",
    @"Goudy",
    @"Grasse",
    @"Gray",
    @"Greely",
    @"Grimsby",
    @"Hadley",
    @"Haineau",
    @"Halden",
    @"Hales",
    @"Halsey",
    @"Halstead",
    @"Ham",
    @"Hamlin",
    @"Hampton",
    @"Hanley",
    @"Hanna",
    @"Harcourt",
    @"Harding",
    @"Hargill",
    @"Harley;Harleigh;Harlow",
    @"Harrington",
    @"Hartwell",
    @"Hasbrouck",
    @"Hastings",
    @"Hatch",
    @"Hatfield",
    @"Hathaway",
    @"Hatton",
    @"Haverill",
    @"Hayden;Haydyn",
    @"Hedges",
    @"Hedon",
    @"Helling",
    @"Henley",
    @"Herndon",
    @"Hernshaw",
    @"Heyden",
    @"Hinckley",
    @"Hindon;Hinton",
    @"Hippisley",
    @"Hipwood",
    @"Holbech",
    @"Holland",
    @"Holme;Holmes",
    @"Holsapple",
    @"Holt",
    @"Holywell",
    @"Hope",
    @"Horton",
    @"Hosford",
    @"Hough",
    @"Houghton",
    @"Houston",
    @"Hubbell",
    @"Huddleston",
    @"Hull",
    @"Hungerford",
    @"Huntley",
    @"Hutton",
    @"Hyde",
    @"Incledon",
    @"Ingham",
    @"Ingleby;Ingoldsby",
    @"Ipres",
    @"Ireton",
    @"Irving;Irvine",
    @"Isabel",
    @"Isham",
    @"Islip",
    @"Ives",
    @"Kay",
    @"Keith",
    @"Kelsey",
    @"Kelso",
    @"Kendall",
    @"Kent",
    @"Kettle",
    @"Kilburne",
    @"Kilham",
    @"Kinghorn",
    @"Kingston",
    @"Kinloch",
    @"Kirby",
    @"Kirkaldy",
    @"Kirkham",
    @"Kirkpatrick",
    @"Knox",
    @"Kyle",
    @"Lacy",
    @"Lancaster",
    @"Langton",
    @"Laycock",
    @"Lechmere",
    @"Leigh;Legh",
    @"Leland",
    @"Lester;Leicester;Leycester",
    @"Leven",
    @"Lewes",
    @"Lewknor",
    @"Lincoln",
    @"Lindall",
    @"Lindsay;Lindsey",
    @"Linn;Linne",
    @"Linton",
    @"Lippencot",
    @"Lismore",
    @"Livingstone",
    @"Lonsdale",
    @"Ludlow",
    @"Main;Mayne",
    @"Mansfield",
    @"Mansle",
    @"Mar",
    @"Massey;Massie",
    @"Mayo",
    @"Mead",
    @"Medcaf",
    @"Menteth;Monteith",
    @"Merton",
    @"Meyeul",
    @"Middleditch",
    @"Middleton",
    @"Milbourne",
    @"Mills",
    @"Milthorpe",
    @"Milton",
    @"Moffatt",
    @"Monroe",
    @"Morley",
    @"Moseley",
    @"Moxley",
    @"Mundy",
    @"Munsel",
    @"Murray;Moray",
    @"Nairne",
    @"Nance",
    @"Needham",
    @"Newton",
    @"Nisbett",
    @"Nogent",
    @"Norcutt;Northcote",
    @"Norfolk",
    @"Northop",
    @"Northumberland",
    @"Norton",
    @"Norwich",
    @"Nottingham",
    @"Oakham",
    @"Ockham",
    @"Ogilvie",
    @"Ollendorff",
    @"Olmstead",
    @"Onslow",
    @"Orchard",
    @"Orr",
    @"Orton",
    @"Otter",
    @"Ouseley",
    @"Oxford",
    @"Pangbourn",
    @"Paris",
    @"Parret;Perrot",
    @"Parsall",
    @"Parshall",
    @"Paxton",
    @"Pedin",
    @"Peebles",
    @"Peele",
    @"Pelham",
    @"Pendleton",
    @"Peney",
    @"Pennington",
    @"Percy;Piercy;Percey",
    @"Pevensey",
    @"Pickering",
    @"Pickersgill",
    @"Playfair",
    @"Pleasants",
    @"Polley",
    @"Pollock",
    @"Poole",
    @"Poulton",
    @"Pressley",
    @"Preston",
    @"Pringle",
    @"Radcliff",
    @"Ralston",
    @"Ramsey",
    @"Ranney",
    @"Rawdon",
    @"Reddenhurst",
    @"Rhodes",
    @"Riddell",
    @"Ripley",
    @"Rochester",
    @"Romanno",
    @"Root",
    @"Rowe",
    @"Rowen",
    @"Rue",
    @"Rusbridge",
    @"Rutherford",
    @"Rynders",
    @"Safford",
    @"Sandford",
    @"Saterlee",
    @"Scarret",
    @"Scroggs",
    @"Seaford",
    @"Seaforth",
    @"Seaton",
    @"Selby",
    @"Selkirk",
    @"Seton",
    @"Severn",
    @"Shaddock;Schadeck",
    @"Shelley",
    @"Sheppy",
    @"Shiel",
    @"Shrewsbury",
    @"Shuckburgh",
    @"Shurtliff",
    @"Shute",
    @"Slade",
    @"Snodgrass",
    @"Soule",
    @"Southwell",
    @"Spalding",
    @"St. Albans",
    @"Stanhope",
    @"Stanley",
    @"Stebbins;Stubbins",
    @"Stein",
    @"Stirling",
    @"Stocking",
    @"Stockton",
    @"Stokes",
    @"Stokesby;Stukeby",
    @"Stone",
    @"Stoughton",
    @"Strain",
    @"Sunderland",
    @"Surtees",
    @"Sutton",
    @"Swift",
    @"Swinburn",
    @"Symington",
    @"Tabor",
    @"Tattersall",
    @"Teddington",
    @"Teesdale",
    @"Tefft;Teft",
    @"Telfair",
    @"Telford",
    @"Temes",
    @"Thorn",
    @"Thurston",
    @"Thwaite;Thwaytes",
    @"Tichenor",
    @"Tillinghast",
    @"Tilton",
    @"Ting",
    @"Torry",
    @"Toucey",
    @"Tournay",
    @"Tracy;Tracey",
    @"Troublefield",
    @"Trowbridge",
    @"True",
    @"Tuthill;Tuttle",
    @"Twickenham",
    @"Van Alstyne",
    @"Van Amee;Van Namen;Van Name",
    @"Van Arden;Van Aerden;Van Orden",
    @"Van Arnhem;Van Arnum;Van Ornum",
    @"Van Dam",
    @"Van Horn;Van Hoorn",
    @"Van Huisen;Van Hoosen;Van Husen",
    @"Van Ingen",
    @"Van Loon",
    @"Van Ness",
    @"Van Rensselaer",
    @"Van Schaack;Van Schaick;Van Scheyk",
    @"Van Slyck",
    @"Van Stantvoordt",
    @"Van Volkenburg",
    @"Van Vorst;Van Voorst",
    @"Van Woert;Van Wort",
    @"Van Wyck",
    @"Vesey",
    @"Vielle;Velay",
    @"Vine",
    @"Waite",
    @"Wakefield",
    @"Wallop",
    @"Walpole",
    @"Walton",
    @"Wample;Wemple",
    @"Wands",
    @"Warburton",
    @"Wardlaw",
    @"Ware",
    @"Warwick",
    @"Washington",
    @"Wassen",
    @"Waters",
    @"Way",
    @"Wayland;Weyland",
    @"Weeden",
    @"Welby",
    @"Welden",
    @"Wells",
    @"Wemyss",
    @"Wentworth",
    @"Westmoreland",
    @"Wetherby",
    @"Wetherspoon;Witherspoon;Wodderspoon",
    @"Wheaton",
    @"Whittaker",
    @"Wigan;Wiggin",
    @"Wilberforce",
    @"Willoughby",
    @"Wilton",
    @"Wiltshire",
    @"Winch",
    @"Winchester",
    @"Windham",
    @"Windsor",
    @"Wing",
    @"Wingfield",
    @"Winslow",
    @"Winterton",
    @"Winthrop",
    @"Wire;Weir;Ware",
    @"Wiswall",
    @"Wolsey;Woolsey",
    @"Woolley",
    @"Worcester",
    @"York" ];
    
    NSArray *stateLocations = @[ @"US-AL:Alabama:state",
    @"US-AK:Alaska:state",
    @"US-AZ:Arizona:state",
    @"US-AR:Arkansas:state",
    @"US-CA:California:state",
    @"US-CO:Colorado:state",
    @"US-CT:Connecticut:state",
    @"US-DE:Delaware:state",
    @"US-FL:Florida:state",
    @"US-GA:Georgia:state",
    @"US-HI:Hawaii:state",
    @"US-ID:Idaho:state",
    @"US-IL:Illinois:state",
    @"US-IN:Indiana:state",
    @"US-IA:Iowa:state",
    @"US-KS:Kansas:state",
    @"US-KY:Kentucky:state",
    @"US-LA:Louisiana:state",
    @"US-ME:Maine:state",
    @"US-MD:Maryland:state",
    @"US-MA:Massachusetts:state",
    @"US-MI:Michigan:state",
    @"US-MN:Minnesota:state",
    @"US-MS:Mississippi:state",
    @"US-MO:Missouri:state",
    @"US-MT:Montana:state",
    @"US-NE:Nebraska:state",
    @"US-NV:Nevada:state",
    @"US-NH:New Hampshire:state",
    @"US-NJ:New Jersey:state",
    @"US-NM:New Mexico:state",
    @"US-NY:New York:state",
    @"US-NC:North Carolina:state",
    @"US-ND:North Dakota:state",
    @"US-OH:Ohio:state",
    @"US-OK:Oklahoma:state",
    @"US-OR:Oregon:state",
    @"US-PA:Pennsylvania:state",
    @"US-RI:Rhode Island:state",
    @"US-SC:South Carolina:state",
    @"US-SD:South Dakota:state",
    @"US-TN:Tennessee:state",
    @"US-TX:Texas:state",
    @"US-UT:Utah:state",
    @"US-VT:Vermont:state",
    @"US-VA:Virginia:state",
    @"US-WA:Washington:state",
    @"US-WV:West Virginia:state",
    @"US-WI:Wisconsin:state",
    @"US-WY:Wyoming:state",
    @"US-DC:District of Columbia:district",
    @"US-AS:American Samoa:outlying territory",
    @"US-GU:Guam:outlying territory",
    @"US-MP:Northern Mariana Islands:outlying territory",
    @"US-PR:Puerto Rico:outlying territory",
    @"US-UM:United States Minor Outlying Islands:outlying territory",
    @"US-VI:Virgin Islands, U.S.:outlying territory" ];
    
    NSUInteger i = 0;
    for (NSString *lastName in lastNames) {
        NSArray *lastNameVariations = [lastName componentsSeparatedByString:@";"];
        for (NSString *lastNameVariation in lastNameVariations) {
            for (NSString *firstName in firstNames) {
                NSArray *components = [firstName componentsSeparatedByString:@":"];
                NSString *firstNameVariationsString = [components objectAtIndex:1];
                NSArray *firstNameVariations = [firstNameVariationsString componentsSeparatedByString:@"/"];
                for (NSString *firstNameVariation in firstNameVariations) {
                    NSMutableString *camelCaseFirstName = [[NSMutableString alloc] initWithCapacity:[firstNameVariation length]];
                    
                    [camelCaseFirstName appendString:[firstNameVariation substringWithRange:NSMakeRange(0, 1)]];
                    [camelCaseFirstName appendString:[[firstNameVariation substringWithRange:NSMakeRange(1, [firstNameVariation length] - 1)] lowercaseString]];
                    
                //make the email address first initial.lastname@test.com
                    NSString *emailAddress = [[NSString stringWithFormat:@"%@.%@@test.com", [camelCaseFirstName substringToIndex:1], lastNameVariation] lowercaseString];
                    
                    Person *p = [NSEntityDescription insertNewObjectForEntityForName:@"Person" inManagedObjectContext:_coreDataController.mainThreadContext];
                    p.firstName = camelCaseFirstName;
                    p.lastName = lastNameVariation;
                    p.emailAddress = emailAddress;
                    p.recordUUID = [[NSUUID UUID] UUIDString];
                    p.stateISOCode = [[[stateLocations objectAtIndex:(i % [stateLocations count])] componentsSeparatedByString:@":"] objectAtIndex:0];
                    i++;
                }
            }
        }
        
    }
    
    [_coreDataController.mainThreadContext performBlockAndWait:^{
        [_coreDataController.mainThreadContext save:nil];
    }];
}